name: api_spec_to_dart
description: Convert Swagger, Postman, and other API specification formats to Dart code
version: 1.0.0
homepage: https://github.com/masreplay/api_spec_to_dart
issue_tracker: https://github.com/masreplay/api_spec_to_dart/issues
funding: [https://github.com/sponsors/masreplay]
topics: [swagger, openapi, postman, freezed, retrofit]

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
dependencies:
  postman_collection: ^0.0.9
