include: package:lints/recommended.yaml

linter:
  rules:
    require_trailing_commas: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"

  errors:
    invalid_annotation_target: ignore