swagger_to_dart:
  # From FastAPI project running locally for example
  # url: http://0.0.0.0:8004/openapi.json

  # Where to save the openapi.json file
  input_directory: schema/swagger.json

  skipped_parameters:
    - "Accept-Language"
    - "X-Language"
    - "X-Platform"
