swagger_to_dart:
  # From FastAPI project running locally for example
  # url: http://0.0.0.0:8004/openapi.json

  # Where to save the openapi.json file
  input_directory: schema/swagger.json

  model:
    support_generic_arguments: true
  api_client:
    skipped_parameters:
      - "Accept-Language"
      - "X-Language"
      - "X-Platform"
